name: Remote Dispatch Action Initiator

on:
  # Trigger the workflow on pr closed,
  # but only for the master branch
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  receiver-update:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating repository event
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, ${{ secrets.DISPATCH_TAG }})
        run: |
          curl -X POST https://api.github.com/repos/s-ashwinkumar/repodispatch-sample-receiver/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_ACCESS_TOKEN }} \
          --data '{"event_type": "update_packages"}'
